# Generated by Django 2.0.3 on 2018-04-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='smsnumber',
            name='sent_intro',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
