# Generated by Django 2.0.3 on 2018-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0003_auto_20180402_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnumber',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
