# Generated by Django 2.0.3 on 2018-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0005_auto_20180402_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnumber',
            name='reminder_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='smsnumber',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
