# Generated by Django 2.0.3 on 2018-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0006_auto_20180402_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnumber',
            name='reminder_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
