# Generated by Django 2.0.3 on 2018-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0007_auto_20180402_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnumber',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
