# Generated by Django 2.0.3 on 2018-04-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0010_auto_20180402_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_mgr.Message')),
                ('sms_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_mgr.SmsNumber')),
            ],
        ),
    ]
