# Generated by Django 2.0.3 on 2018-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0011_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
