# Generated by Django 2.0.3 on 2018-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0012_auto_20180402_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsnumber',
            name='reminder_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
