# Generated by Django 2.0.3 on 2018-04-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0013_auto_20180402_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
