# Generated by Django 2.0.3 on 2018-04-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0017_auto_20180404_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnumber',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='smsnumber',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_mgr.Location'),
        ),
    ]
