# Generated by Django 2.0.3 on 2018-04-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0018_auto_20180404_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnumber',
            name='firebase_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
