# Generated by Django 2.0.3 on 2018-04-12 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0019_smsnumber_firebase_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('sent_intro', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('firebase_id', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='twilio_mgr.Location')),
            ],
        ),
    ]
