# Generated by Django 2.0.3 on 2018-04-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_mgr', '0023_auto_20180420_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='message',
            field=models.CharField(max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sms_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
